### ISSUE TITLE
Не отображается лого в кастомной теме, файл при этом есть, ссылка на него указана в ксс корректно

### ISSUE THREAD

**Issue by JohnLyetacker** [SCPru/RuFoundation#101]
https://scpfoundation.net/theme:thalassophobia-sigma

https://files.scpfoundation.net/local--files/theme:thalassophobia-sigma/logo.svg

**Comment by jewalky** [comment]
Ссылка указана в ксс некорректно.

Для компонента нужно добавить https://scp-wiki.wikidot.com/component:centered-header-sigma-9 и грузить вместе с темой

Ты бы хоть проверил ссылается ли что-то на странице на --lgurl
Конечно само по себе оно ничего делать не будет
