### ISSUE TITLE
В модуле listpages не работает блок изображений

### ISSUE THREAD

**Issue by ParussMan** [SCPru/RuFoundation#104]
https://scpfoundation.net/scp-5410
Пример здесь
![изображение](https://user-images.githubusercontent.com/79791478/187773377-f414c0a5-52ab-4963-bd92-211aad8a20ec.png)
![изображение](https://user-images.githubusercontent.com/79791478/187773404-6cf9063e-cb91-48c4-9d2b-fb7b2afd01d1.png)
Фото загружено, если вырезать модуль оно отображается.

**Comment by jewalky** [comment]
Это, как бы, норма, и на викидоте оно тоже не отображается.
http://scp-ru.wikidot.com/scp-5410

При использовании картинок в module listpages (во всяком случае separate="yes" или без указания separate) картинка будет отрисована с той страницы, которая в данный момент отображается в listpages.

В случае с викидотом я там вижу members:main/two.jpeg
У нас scp-4251... в общем это непредсказуемо, чините на своей стороне

**Comment by ParussMan** [comment]
ээ ну я после объяснения придумал как починить можно это на своей стороне, если кто-то еще столкнется пусть тож попробует: указать url на загруженный в статью файл
вроде помогает
