### ISSUE TITLE
Не рендерится [[tabview]]

### ISSUE THREAD

**Issue by JohnLyetacker** [SCPru/RuFoundation#105]
В хабе КСИР:
https://scpfoundation.net/oria-hub
А еще то же самое в списке авторства:
https://scpfoundation.net/licensing
И в объектах тоже:
https://scpfoundation.net/scp-2746

**Comment by jewalky** [comment]
Такое происходит, когда в середине табвью есть какой-то невалидный синтаксис.

**Comment by jewalky** [comment]
Я исправил баг, который заставлял всю страницу пердолиться. Остальное на совести редакторов

**Comment by jewalky** [comment]
В лицензировании всё попердолено из-за этого
![image](https://user-images.githubusercontent.com/5638098/188054470-cc31e482-2017-41be-8079-cd0ddcc48e38.png)

В хабе КСИР из-за этого
![image](https://user-images.githubusercontent.com/5638098/188054507-25371943-fee7-4152-91d7-5d0dac3b601a.png)
Возможно из-за этого
![image](https://user-images.githubusercontent.com/5638098/188054553-a921672e-dd0c-466f-aa9b-8557c916f76c.png)
