### ISSUE TITLE
Сгенерировано пустое место в статье, где оно никаким образом не задается

### ISSUE THREAD

**Issue by JohnLyetacker** [SCPru/RuFoundation#106]
https://scpfoundation.net/scp-4251

**Comment by ParussMan** [comment]
> Скриншот. Не вижу.

![изображение](https://user-images.githubusercontent.com/79791478/188055515-5bbc2a26-a530-4754-8ca0-019bbaa9eb15.png)
Если что я спросил Джонича и он сказал что это имел ввиду. Самому мне кажется, что так и должно быть.

**Comment by jewalky** [comment]
Да, это не баг, у страницы фиксированная высота
