### ISSUE TITLE
Ошибки при попытке открыть scp-2111

### ISSUE THREAD

**Issue by JohnLyetacker** [SCPru/RuFoundation#107]
https://scpfoundation.net/scp-2111
![изображение](https://user-images.githubusercontent.com/44590586/188174966-eb236e6e-9a96-4409-888c-0f9c463f1f3f.png)
![изображение](https://user-images.githubusercontent.com/44590586/188174977-7b5417a8-7b20-46cc-80cb-d91689ce8ec7.png)

**Comment by jewalky** [comment]
Исправлено. В подобных случаях приписывайте /noredirect/true и смотрите откуда редирект взялся
