### ISSUE TITLE
Предложение: добавить кнопку для копирования всего исходника статьи

### ISSUE THREAD

**Issue by ParussMan** [SCPru/RuFoundation#108]
Сделать кнопочку, по нажатии которой волшебно копируется содержимое кода статьи для менюшки снизу и при просмотре правки

**Comment by jewalky** [comment]
Сейчас это делается двумя кнопками: ctrl+a ctrl+c

**Comment by ParussMan** [comment]
Блять, точно 
Но мне кажется ты бы мог мне напомнить об этом и в лс дискорда :рофлан:
