### ISSUE TITLE
Вопрос наказаний

### ISSUE THREAD

**Issue by User-green** [SCPru/RuFoundation#11]
Итак, товарищи. Вам, я думаю, хорошо известно, что на Викидоте вопросс наказаний решался просто — баном, без вариантов. 
Сейчайс же, когда пишется новый движёк, возникает вопрос: а может, стоит сделать возможность раздельных наказаний? Например: только запрет на редактирование. Или только запрет на оценку. Или только на комментрарии.
Думаю, подобная фича, совмещённая с правильной политикой, будет поошерять честное отбытие наказаний и вразумление народа, а не пложение альтов.

**Comment by jewalky** [comment]
Мне кажется, что этот вопрос не имеет напрямую отношения к разработке сайта. Закрыто.

Несмотря на то, что этот гитхаб иногда читают АМС, задавать организационные вопросы АМС стоит всё же не здесь :)
