### ISSUE TITLE
Спойлер можно закрыть только верхней кнопкой закрытия, если их 2

### ISSUE THREAD

**Issue by JohnLyetacker** [SCPru/RuFoundation#110]
Если для спойлера задана возможность закрывать в двух местах - начале и конце - то он закрывается только верхней ссылкой
Пример:
https://scpfoundation.net/translations-planning
Раздел "Готовящиеся переводы статей"

**Comment by jewalky** [comment]
Исправлено в b248c20 / c2242f8
