### ISSUE TITLE
Нет проверки логина на форме регистрации (signup)

### ISSUE THREAD

**Issue by fallenss** [SCPru/RuFoundation#119]
Нету проверки на уже существующий логин, в случае совпадения влетает ошибка.

![изображение](https://user-images.githubusercontent.com/101922436/191251705-ebefd330-335a-4935-ad62-256941b8eb16.png)

**Comment by jewalky** [comment]
Поправка: проверять оба юзернейма (викидотовский и обычный). Если хоть один совпадает, не давать создавать ничего

**Comment by jewalky** [comment]
Внезапно исправлено в 2023 году в 57a4ad5cd92f4bdde26bea5d44ce91480d52bc00
