### ISSUE TITLE
Установление родительской страницей саму страницу создает Bag Gateway на ней и на всей цепочке, где установлена она

### ISSUE THREAD

**Issue by ParussMan** [SCPru/RuFoundation#122]
ПРАКТИЧЕСКИМ ПУТЕМ БЫЛО УСТАНОВЛЕНО, ЧТО:

https://scpfoundation.net/draft:parussman
https://scpfoundation.net/draft:foundationprehnia
https://scpfoundation.net/draft:parussman2

Выдают ошибку Bad Gateway при заходе, потому что у меня было желание провести эксперимент и установить родительской страницей на первом черновике сам черновик. А в связи с тем, что два других были привязаны к первому, то они тоже более недоступны. Пожалуйста почините я не хочу терять 1500 правок.

**Comment by jewalky** [comment]
Исправлено ff08300
