### ISSUE TITLE
Правки %%revisions%% в модуле listpages отображаются некорректно

### ISSUE THREAD

**Issue by ParussMan** [SCPru/RuFoundation#123]
https://scpfoundation.net/draft:test-include

Пример тут (почти), допустим на моем черновике показывает 1215 правок, хотя там их уже больше. Полагаю, эти правки считаются с момента изменения заголовка, не могу проверить в данный момент

**Comment by jewalky** [comment]
Это как-то очень дико звучит, по-моему это пиздёж

**Comment by jewalky** [comment]
Ладно там был баг
