### ISSUE TITLE
Добавить сортировку тэгов по категориям

### ISSUE THREAD

**Issue by jewalky** [SCPru/RuFoundation#126]
т.е. вместо сваливания ru, евклид, рассказ, и т.д. в один список, должна быть возможность указать, что "ru" это тэг филиала, "евклид" — класса, а "рассказ" — технический.

Смысл в том, что сейчас считается возможным добавлять только тэги первого приоритета, т.к. остальные будут слишком сильно засирать список и в нём ничего нельзя будет найти (во всяком случае, такая официальная мотивация).

Если будет разделение на категории, то можно будет добавить тэг "кот" и не опасаться, что под тоннами таких "котов" будут погребены тэги свор или ещё чего-нибудь.

**Comment by jewalky** [comment]
Технические пункты:

- показ тэгов в списке под страницей с сортировкой по категориям [значимость не доказана]
- показ тэгов в облаке с сортировкой по категориям
- iftags / listpages с необязательным указанием точной категории

**Comment by MrNereof** [comment]
Добавлено
