### ISSUE TITLE
Некорректная работа модуля rate в статье с offsetами

### ISSUE THREAD

**Issue by fallenss** [SCPru/RuFoundation#129]
Статья: https://scpfoundation.net/sandbox:scp-194

Не отображается рейтинг, хотя оценки есть:
![изображение](https://user-images.githubusercontent.com/101922436/196607736-ac04eea9-0f9a-4ad7-874d-61f4d57b2975.png)

В самой статье видно что оценки есть (в модуле справа сверху), но в кнопке "Оценить" оценка не указана и по нажатию на неё не отображаются пользователи и их оценки.

**Comment by jewalky** [comment]
Переписывай таким образом чтобы статья выглядела точно так же как в англовики
Я намекну
У НИХ МОДУЛЬ РЕЙТА НАХОДИТСЯ В СЦП 194 А НЕ В ОФФСЕТЕ
(я просто удивлён как у тебя проблемы с этой страницей уже во второй раз, и оба раза они решаются копированием кода из англовики)
