### ISSUE TITLE
Что-то не так с разметкой в личном деле Клевера

### ISSUE THREAD

**Issue by ParussMan** [SCPru/RuFoundation#131]
https://scpfoundation.net/cleverempty-personnel-file

Не знаю как это объяснить, вот короче 
![изображение](https://user-images.githubusercontent.com/79791478/197206112-2b848034-6aed-481f-8c16-574b7738d976.png)

Это как выглядит статья. 

А вот как она выглядит в предпросмотре
![изображение](https://user-images.githubusercontent.com/79791478/197206219-af9ff69d-a2f6-4757-86d3-42e62eb0219d.png)

Полагаю, что правильный вариант второй

**Comment by jewalky** [comment]
Полностью соответствует поведению викидота. Не ко мне

![image](https://user-images.githubusercontent.com/5638098/197344889-29d06632-7fba-4c2f-8909-5e898de42c62.png)
