### ISSUE TITLE
Выпадающее меню из топбара вылазит за рамки страницы на мобилках

### ISSUE THREAD

**Issue by ParussMan** [SCPru/RuFoundation#132]
![Screenshot_2022-10-21-22-20-20-518_](https://user-images.githubusercontent.com/79791478/197257067-499d246c-6cb1-4c04-b59d-01915909b349.jpeg)

Проверял на мобильном FireFox, хз какая еще инфа нужна если честно, по-моему там на всех узких экранах такое происходит.

**Comment by jewalky** [comment]
Это не баг движка сайта
