### ISSUE TITLE
Неверно создаются ссылки для тегов с символом "/" в теле

### ISSUE THREAD

**Issue by Aarzang** [SCPru/RuFoundation#140]
Неверно создаются ссылки для тегов с символом "/" в теле

Пример:
https://scpfoundation.net/system:page-tags/tag/растение/гриб

В таком виде система распознаёт её неправильно и из-за этого не отображает статьи по тегу.

**Comment by MrNereof** [comment]
Предлагаю заменить / в названиях тегов на |

**Comment by Aarzang** [comment]
Да это вообще временные обозначения, сейчас такие теги будут разбиваться на вменяемые наборы тегов поменьше. Проблема в том что как для этого так и для замены "/" на "|" нужен список статей с тегом в текущем виде, а как раз этот список из-за бага не отображается.

**Comment by jewalky** [comment]
Предлагаю ничего ни на что не заменять.
Если символ `/` в названиях тэгов разрешён и работает, а у сайта на нём делает derp moment, то надо чинить.

**Comment by Rhombus-H** [comment]
Аналогичное с символом решётки - "#".

**Comment by MrNereof** [comment]
@Aarzang , на будущее уточню, что для изменения тега его достаточно переименовать в админке
