### ISSUE TITLE
В "Недавно созданные статьи" отображаются страницы, которые были созданы давно, а указанные правки не существуют

### ISSUE THREAD

**Issue by JohnLyetacker** [SCPru/RuFoundation#141]
https://scpfoundation.net/most-recently-created
![Untitled](https://user-images.githubusercontent.com/44590586/198820396-3c9ee369-13b0-44ac-9ef0-b9b9337a44ca.png)

Одна из страниц:
https://scpfoundation.net/scp-179
![изображение](https://user-images.githubusercontent.com/44590586/198820444-a10b3777-5622-4feb-a5aa-fed10c24b3f5.png)

**Comment by ParussMan** [comment]
Эти страницы это редирект на переведенные материалы

**Comment by JohnLyetacker** [comment]
Выразим Анонимусу спасибо за лишнюю работу в Дискорде
