### ISSUE TITLE
Некорректное отображение текста  в содержании

### ISSUE THREAD

**Issue by RikCost** [SCPru/RuFoundation#143]
https://scpfoundation.net/canon-hub##
![IMG_20221029_122000](https://user-images.githubusercontent.com/69048938/198824362-5f35083e-31cd-4bcb-9ce4-571030f01b28.jpg)

**Comment by MrNereof** [comment]
Что подразумевается под некоректным содержанием? Ссылки после заголовков?

**Comment by jewalky** [comment]
Дублирует https://github.com/SCPru/RuFoundation/issues/87
