### ISSUE TITLE
Не распознаются переменные, используемые в _template

### ISSUE THREAD

**Issue by JohnLyetacker** [SCPru/RuFoundation#145]
В Викидоте была куча переменных:
https://www.wikidot.com/doc:templates

Можно добавить хотя бы одну малюсенькую %%fullname%% ?

Чтобы можно было с помощью такой вот конструкции
![изображение](https://user-images.githubusercontent.com/44590586/200203973-4d06ff4b-5185-4c40-872c-212b1aa494f1.png)

сделать разом для всех тем вот так
![изображение](https://user-images.githubusercontent.com/44590586/200204006-7d8d1207-489e-4392-b891-66c1d51bb077.png)

(и для каждой темы будет отображаться свой индивидуальный текст ссылки на себя для включения куда-либо)

**Comment by ParussMan** [comment]
В текущий момент это можно сделать так
https://scpfoundation.net/draft:parussnetech#

**Comment by jewalky** [comment]
По идее можно прикрутить переменные от листпагес сюда

**Comment by jewalky** [comment]
п.с. хак паруса не нужен

**Comment by ParussMan** [comment]
п.с. хак паруса немног не работает потому что в темплейт как оказалось content не превращается в инклуд, но на самом деле можно было бы заменить на [[include %%fullname%%]] внутри листпейджеса, но да, в целом не нужен
