### ISSUE TITLE
Добавить "популярность" (рабочее название) как параметр рейтинга статьи (и позволить по нему сортировать через листпейджес)

### ISSUE THREAD

**Issue by Aarzang** [SCPru/RuFoundation#148]
Добавить "популярность" (рабочее название) как параметр рейтинга статьи (и позволить по нему сортировать через листпейджес)

Параметр рассчитывается через выражение: (количество оценок 3.0 и выше)/(общее число оценок). 

Отображается в нижней строке общего модуля рейтинга, процентами. Пример:
![image](https://user-images.githubusercontent.com/29339536/201688237-e8e56b94-dbe6-4544-a37d-edf42b02ea03.png)
8 оценок из 11 имеют значение 3.0 или выше. Следовательно итоговое значение 8/11 = примерно 73%. Отображаемый вид:
![image](https://user-images.githubusercontent.com/29339536/201688816-3fb7155f-f685-49aa-8bf9-1b7c21b856c2.png)

**Comment by ParussMan** [comment]
Тогда придется удлиннять модуль? Ибо строку голосов стоило бы оставить все-таки
