### ISSUE TITLE
Блок сносок отображается под любым инклудом

### ISSUE THREAD

**Issue by Int096** [SCPru/RuFoundation#15]
https://scpfoundation.net/scp-1380-ru  - Блок сносок вверху страницы. (Предположительно, такое везде.)

**Comment by ParussMan** [comment]
Нужно включить поддержку >=, <=, >, < в rate, created_at и возможно ещё где-нибудь

**Comment by ParussMan** [comment]
https://scpfoundation.net/scp-4812 - похожая проблема, сноски повторяются многоразово

**Comment by jewalky** [comment]
Исправлено db208bd
