### ISSUE TITLE
Листпейджс — доделать параметры date, rating, created_by, добавить поля шаблона updated_by, tags

### ISSUE THREAD

**Issue by ParussMan** [SCPru/RuFoundation#16]
Допилить параметры модуля листпейджс, чтобы тот корректно работал

Фильтр:
- [x] date
- [x] rating
- [x] created_by

Шаблон:
- [x] %%updated_by%% и аналоги
- [x] %%tags%% и %%tags_linked%%

**Comment by jewalky** [comment]
Конкретно: date, rating.

Заодно по возможности сделать поля шаблона которые сейчас не реализованы — %%updated_by%%, %%tags%% и т.п.

**Comment by MrNereof** [comment]
Допилил

**Comment by jewalky** [comment]
478c393
