### ISSUE TITLE
Слёт кодировки компонента Svgheader

### ISSUE THREAD

**Issue by Dugond** [SCPru/RuFoundation#164]
У англиков есть [компонент](https://scp-wiki.wikidot.com/component:svgheader-backend) для создания Красивого (тм) заголовка, вот [пример](https://scp-wiki.wikidot.com/fragment:jack-ike-s-proposal-ii-4), как должен он выглядеть. В [нашей версии](https://scpfoundation.net/component:svgheader1-base-base) компонента что-то не работает, в результате чего вместо заголовка вываливается часть изначальной кодировки.

**Comment by jewalky** [comment]
Нефиксабельно, сделано через жопу в оригинале

**Comment by Dugond** [comment]
Понял, тогда заменяю рабочими аналогами, как и cd-ver2, там такая же история.

**Comment by Vladg24YT** [comment]
Прошу прощения за некропостинг, но пофикшено через разметку переменных.
