### ISSUE TITLE
Сломался iframe

### ISSUE THREAD

**Issue by Dugond** [SCPru/RuFoundation#165]
Собственно, сабж. Выдаёт [такое](https://user-images.githubusercontent.com/127948948/225639336-a0e1cc52-1082-45dc-8ec5-41822a45bcac.png) прям в статье с оформлением.

**Comment by Dugond** [comment]
[Вот с мобильного Хрома](https://user-images.githubusercontent.com/127948948/225647633-b217bcc7-9fa7-4b37-83f7-2b98752594d2.jpg), такая же история.

**Comment by jewalky** [comment]
Мы не виноваты в том, что сайт нельзя открыть в фрейме

Откройте что-нибудь другое что разрешает себя открывать в фрейме....
