### ISSUE TITLE
Интеграция латеха (формулы)

### ISSUE THREAD

**Issue by Dugond** [SCPru/RuFoundation#166]
А есть возможность как-то интегрировать[ сервис по написанию/отображению формул](https://www.mathjax.org/)? Не прям сильная необходимость, страниц с ними не так и много, хватает и прямой вставки скрипта, но если это не очень сложно, то почему нет.

**Comment by jewalky** [comment]
Возможность есть, но для одних реализаций это небезопасно с т/з XSS, а другие реализации кривую картинку дают. Поэтому было отложено

**Comment by jewalky** [comment]
В матъяксе буквально находят хсс каждый день (ладно не буквально но порядок проблемы понятен должен быть)
