### ISSUE TITLE
Обновить Сигму-9 до 10 (частично)

### ISSUE THREAD

**Issue by ParussMan** [SCPru/RuFoundation#169]
По чуть-чуть обновить тему сайта:
- шрифт в тексте
- шрифт в заголовке
- новое лого, новый БГ (без прозрачности)
- жирный шрифт в подписях картинок

Частично есть здесь https://scpfoundation.net/draft:search2

**Comment by LimitR** [comment]
Мб лучше это в рамках пулреквеста сделать?
