### ISSUE TITLE
Некорректное отображение страницы "Свежие правки" на мобильном Google Chrome.

### ISSUE THREAD

**Issue by MeatOasis** [SCPru/RuFoundation#170]
Ссылки на страницы, к которым была применена правка, отображаются не горизонтально, а вертикально, см. скриншот.
![image](https://github.com/SCPru/RuFoundation/assets/111533119/33dd2c63-a275-4b1c-937f-e4291e695c88)

**Comment by ParussMan** [comment]
исправлено на странице правок
