### ISSUE TITLE
Ввести панель статистики

### ISSUE THREAD

**Issue by JohnLyetacker** [SCPru/RuFoundation#173]
Ввести учет статистики посещаемости сайта, отражающую количество посещений на промежутки времени, данные об устройствах (мобильные/десктоп). Разместить панель на администратоской/модераторской странице, либо сделать публичной.

**Comment by jewalky** [comment]
Частично делается через гугл аналитикс, возможно можно как-то прикрутить

**Comment by jewalky** [comment]
Уже сделано через гугл аналитикс, ответственный тех-стафф — ParussMan

Если будет нужно переоткроем
