### ISSUE TITLE
Модуль user внутри ссылок <a> не подтягивает стили (?)

### ISSUE THREAD

**Issue by ParussMan** [SCPru/RuFoundation#180]
![изображение](https://github.com/SCPru/RuFoundation/assets/79791478/15e8511c-1ea1-4fdf-b1ed-e98f12818dc5)
И
![изображение](https://github.com/SCPru/RuFoundation/assets/79791478/89f4994c-b48c-4941-b6c3-9b4a8e40f787)

**Comment by ParussMan** [comment]
![изображение](https://github.com/SCPru/RuFoundation/assets/79791478/b5f72ee8-ddeb-4305-a920-68896a887f1d)
Внутри модуля листпейджес потом еще полная жесть происходит

**Comment by jewalky** [comment]
Нельзя совать <a> внутрь <a>, это буквально невалидный хтмл

https://stackoverflow.com/questions/18666915/why-are-nested-anchor-tags-illegal

Проблема на вашей стороне
