### ISSUE TITLE
Бесконечный цикл импортов image-block-base

### ISSUE THREAD

**Issue by btomaev** [SCPru/RuFoundation#186]
Если в коде страницы вставить image-block-base, а потом image-block второй импорт вылетает с ошибкой: 
`Вставленная страница "component:image-block-base" вызывает бесконечный цикл включений`
Англиковский сайт спокойно переваривает

```
[[include component:image-block-base
|name=12345
|caption=aaaaaaaaaaa
|width=300px]]

[[include component:image-block
|name=12345
|caption=bbbbbbbbbbb
|width=300px]]
```
^^^Бесконечный импорт^^^

```
[[include component:image-block
|name=12345
|caption=aaaaaaaaaaa
|width=300px]]

[[include component:image-block
|name=12345
|caption=bbbbbbbbbbb
|width=300px]]
```
^^^Все ок^^^

Если поменять импорты местами, ошибка сохраняется
![Снимок экрана 2024-01-20 в 20 15 48](https://github.com/SCPru/RuFoundation/assets/65013732/99dfe608-8879-4bba-b072-6f1eea777a21)

Встречается на странице: https://scpfoundation.net/draft:keter-duty в правке 1

**Comment by jewalky** [comment]
Исправлено в d278f13ecf675e61893f297bf5226a46dae308dc
