### ISSUE TITLE
Некоторые заголовки не отображаются в TOC

### ISSUE THREAD

**Issue by Int096** [SCPru/RuFoundation#19]
https://scpfoundation.net/canon-hub

**Comment by jewalky** [comment]
Это не вытянутая обводка, а сломанные заголовки.

http://scp-ru.wikidot.com/canon-hub

Должно быть так:

![image](https://user-images.githubusercontent.com/5638098/182405465-9812e92d-af7b-452a-8cf7-b7496fe289d1.png)

**Comment by jewalky** [comment]
Исправлено
