### ISSUE TITLE
Заголовок не отображается, если это последний элемент в исходнике

### ISSUE THREAD

**Issue by RichardHMus** [SCPru/RuFoundation#24]
(Баг ли хз)

Заголовки работают через раз.
Если просто ввести:
>
> + Заголовок первого уровня

То оно не работает
А вот так:
> 
> + Заголовок первого уровня
> ++ Заголовок второго уровня
> +++ Заголовок третьего уровня
> ++++ Заголовок четвёртого уровня
> +++++ Заголовок пятого уровня

То оно работает
(Тестил в своем черновике)
https://scpfoundation.net/draft:saintly

upd: Плюс в "Заголовок первого уровня" съел гитхаб, на сайте он есть

**Comment by jewalky** [comment]
Не наблюдаю данной проблемы в черновике:

![image](https://user-images.githubusercontent.com/5638098/183789797-86566860-9973-43d7-94ea-8e01663257b6.png)

```
Баг с заголовком
-----

+ Заголовок первого уровня
++ Заголовок второго уровня
+++ Заголовок третьего уровня
++++ Заголовок четвёртого уровня
+++++ Заголовок пятого уровня


+ Заголовок первого уровня


+ SCP-XXXX-RU - Организация N
```

**Comment by jewalky** [comment]
Если имеется в виду что заголовок не работает когда он является последней строкой в статье, то будет исправлено

**Comment by RichardHMus** [comment]
Да, речь была об этом, похоже я не правильно понял суть бага. Спасибо.
