### ISSUE TITLE
Отсутсвует html5player

### ISSUE THREAD

**Issue by RedComet117** [SCPru/RuFoundation#28]
![изображение](https://user-images.githubusercontent.com/110979943/183891961-739d0ebb-5bfc-42eb-b6f9-39044440305c.png)
Пример: https://scpfoundation.net/in-the-trenches-with-the-dead

**Comment by jewalky** [comment]
Нужно создать компонент типа как у арбеликта и пользоваться им вместо html5player
```
[[HTML]]
<html>
<body>
<audio preload="metadata" controls loop>
<source src="http://scpfoundation.net/local--files/scp-002-h/Hopetown%20fall%20%281%29.mp3" >
</audio>
</body>
</html>
[[/HTML]]
```

Не является багом движка.
