### ISSUE TITLE
На странице Стать участником всё ещё висит викидотовский модуль рейтинга.

### ISSUE THREAD

**Issue by glazgoferkins** [SCPru/RuFoundation#30]
Если это валидно, то лучше заменить на отечественный или вовсе отключить голосование на странице.
![image](https://user-images.githubusercontent.com/85983176/183938989-e71d5ac0-c64f-40c7-a620-07f9168e2113.png)

**Comment by jewalky** [comment]
Исправлено / давно исправлено [?]
