### ISSUE TITLE
Не работает функционал сайта на старых устройствах

### ISSUE THREAD

**Issue by Lord-Epikion** [SCPru/RuFoundation#37]
Использовал для просмотра сайта старенький планшет на базе андроида 4.2 с соответствующими версиями браузеров. На викидоте всё работало нормально можно было и писать и править, но с переходом на новый сайт увидел то, что видно на скриншотах. Отсутствуют все кнопки на нижней панели, и кнопка входа и регистрации вверху. Пробовал разные браузеры, переходил на "версию сайта для пк" и смотрел на другом устройстве с андроидом 4.4, проблема во всех случаях остаётся. На более новых устройствах ( андроид 10) всё работает нормально. 

![Screenshot_2022-08-11-08-57-17](https://user-images.githubusercontent.com/111040027/184074239-b903dc5c-e935-470a-8a4a-5274100b2807.png)
![Screenshot_2022-08-11-08-57-27](https://user-images.githubusercontent.com/111040027/184074241-362a15b4-c91d-4dbf-b4f6-6d9e6375bd1f.png)
.

**Comment by jewalky** [comment]
Поддержка настолько древних устройств не в приоритете. Хотя бы 2017+ год пожалуйста. Пока что закрыто.
