### ISSUE TITLE
Чеклист к первому релизу

### ISSUE THREAD

**Issue by jewalky** [SCPru/RuFoundation#4]
- [x] Регистрация пользователей админом через инвайт 
  - [x] Создание пользователя с юзернеймом и емейлом (@MrNereof)
  - [x] Высылание емейла с текстом про инвайт и запросом вида "перейдите на сайт, чтобы подтвердить емейл и установить пароль" (@MrNereof) 
- [x] Логин в админ-панель (@MrNereof)
- [x] Базовый функционал управления сайтом в админке (@MrNereof)
- [x] Логин в пользовательскую часть сайта (@MrNereof) 
- [x] Кнопка "вход" сверху справа + выпадающее меню если юзер залогинен (@jewalky) 
- [x] (опционально) Публичный профиль пользователя (@MrNereof) 
- [x] Редактирования профиля пользователя (как минимум в части пароля, емейла и юзернейма) (@MrNereof) 
- [x] Восстановление пароля через емейл (@MrNereof) 
- [x] Стили для системных страниц (@jewalky) 
- [x] Редактирование страниц
  - [x] Поддержка юзеров в страницах (@MrNereof)
  - [x] Версии в страницах (@jewalky)
  - [x] Поддержка юзеров в версиях страниц (@MrNereof)
  - [x] (опционально) Просмотр предыдущих версий страниц и кнопка вернуть ревизию (@MrNereof)
  - [x] (опционально) Предпросмотр перед сохранением (@MrNereof)
  - [x] Редактирование тэгов (@MrNereof)
  - [x] Загрузка файлов (@jewalky)
  - [x] Установка и снятие родительской страницы (@MrNereof)
  - [x] Смена имени страницы (@MrNereof)
- [x] Блокировка страниц для редактирования только админом (по категориям) (@MrNereof)
- [x] Блокировка отдельных страниц (галочка на конкретной странице) (@MrNereof)
- [x] Рейтинг страниц (@MrNereof, @jewalky)
- [x] Удаление страницы в категорию deleted: (@MrNereof)
- [x] Удаление страницы с концами (@MrNereof)
- [x] Расширенная модель пользователя (@MrNereof)
- [x] Несколько сайтов на одном хостинге (с разделением по доменам) и админка к этому (@jewalky)
- [x] Перевод продуктовой версии сайта в докер и на PostgreSQL (@jewalky)
- [x] Обеспечить высылание емейла на проде (@jewalky)
- [x] Система рейтинга от 0 до 5 (флоатами, по 0.5) (@jewalky)
- [x] Допиливание сидера из архива чтобы восстанавливались все ревизии, файлы и оригинальные юзеры из викидота (@jewalky)

**Comment by User-green** [comment]
Вещи, по моему мнению, в этом списке упущеные:

- [ ] Резервное копирование
- [ ] - - Через админ-панель
- [ ] - - По кронтабу
- [ ] - - Через SSH
- [ ] РАБОЧАЯ функция "Выйти, если мой IP изменится"
- [ ] - - Включить по умолчанию?
- [ ] Защита от викидотовских XSS, если нет
- [ ] Политику конфиденциальности (Я?)
- [ ] Политику обслуживания (Я?)


Дополнительные вещи, которые, возможно, стоит сделать [когда-небудь поже](https://scpfoundation.net/scp-j)


- [ ] Ссылки на страницу на других языках
- [ ] Саморегестрация юзеров
- [ ] - - Сразу предлагать заполнить анкету?
- [ ] - - КАПЧА
- [ ] Приложение для мобилок
- [ ] - - API пользователя
- [ ] - - - - Исходник страницы
- [ ] - - - - Редактирование страницы
- [ ] - - - - Редактирование профиля
- [ ] Фильтры правок (как на Википедии)
- [ ] Опцию бана
- [ ] - - Временного и перма
- [ ] - - - - По Юзеру
- [ ] - - - - По IP (ренджу?)
- [ ] - - - - По фингурпринту
- [ ] - - - - По биосу (вроде как на хабре такое практикуют?)
- [ ] - - А так же защиту от:
- [ ] - - - - Tor
- [ ] - - - - VPN
- [ ] - - - - Proxy
- [ ] - - - - I2P

**Comment by User-green** [comment]
Вещи, по моему мнению, в этом списке упущеные:

- [ ] Резервное копирование
  - [ ] Через админ-панель
  - [ ] По кронтабу
  - [ ] Через SSH
- [ ] РАБОЧАЯ функция "Выйти, если мой IP изменится"
  - [ ] Включить по умолчанию?
- [ ] Защита от викидотовских XSS, если нет
- [ ] Политику конфиденциальности (Я?)
- [ ] Политику обслуживания (Я?)


Дополнительные вещи, которые, возможно, стоит сделать [когда-небудь поже](https://scpfoundation.net/scp-j)


- [ ] Ссылки на страницу на других языках
- [ ] Саморегестрация юзеров
  - [ ] Сразу предлагать заполнить анкету?
  - [ ] КАПЧА
- [ ] Приложение для мобилок
  - [ ] API пользователя
    - [ ] Исходник страницы
    - [ ] Редактирование страницы
    - [ ] Редактирование профиля
- [ ] Фильтры правок (как на Википедии)
- [ ] Опцию бана
  - [ ] Временного и перма
    - [ ] По Юзеру
    - [ ] По IP (ренджу?)
    - [ ] По фингурпринту
    - [ ] По биосу (вроде как на хабре такое практикуют?)
  - [ ] А так же защиту от:
    - [ ] Tor
    - [ ] VPN
    - [ ] Proxy
    - [ ] I2P

**Comment by jewalky** [comment]
1. Резервное копирование является функцией инфраструктуры, а не сайта. То есть если хочется его сделать, надо делать его непосредственно в кроне, средствами докера или чего-либо ещё
2. Функция выхода при изменении IP возможно будет потом и точно не будет включена по умолчанию (из-за телефонов). Можно сделать функцию выхода по каким-нибудь другим признакам. Например изменение юзерагента.
3. Защита от XSS ставится сразу
4. Политика конфиденциальности и обслуживания это чё за хрени? Звучит как что-то европейское и формальное

----

1. Ссылки на страницу на других языках (интервики) — согласен
2. Саморегистрация — согласен. Капча — не уверен, может будет всё та же анкета или сложный вопрос с роботом как у англиков. Причина в том что за капчу платить надо, иначе лимит запросов, который может накрутить бот. То есть следи за руками: бот делает 1000000 запросов, гугл блокирует наш сайт от рекапчи, и никто не может регаться.
3. Приложение для мобилок — не согласен что нужно. Меня всегда бесит вот это "download app" по самым разным причинам. Самая главная — там нет закладок и вкладок от браузера. То есть большинство ебучих приложений в отличие от браузера позволяют просматривать только одну страницу за раз, в то время как в браузере я могу открыть неограниченное количество параллельно. Если делать нормально, то может быть, но тогда повторяем функционал браузера.
4. Пожалуйста разверни предложение. Я не знаю что такое фильтр правок. Но чисто название мне не нравится заранее уже.
5. Не согласен что нужны баны по IP, это будет вечная гонка вооружений. Особенно по части "защиты от тора и впн", это пиздец хуета, ненавижу злоебучее пикабу которое я не могу со своего впн читать.
6. Согласен что нужны обычные баны по юзеру с длительностью или насовсем.

**Comment by User-green** [comment]
1. Согласен, но сделать РК, хоть и на уровне инфраструктуры, совершенно обязательно.

2. Хорошо. Но в любом случае это необходимо, дабы избежать угона сессий. 

3. Хорошо.

4. Да, это всё буржуйское, и за отцуцтвие этих страниц может оччччень сильно прилететь. В плоть до того, что откажутся хостить буржуйские хостеры.

----

2. Просто сделать свою капчу, как на 4pda. Лишний уровень ботофобии, дабы админам не пришлось разгребать 100500 одинаковых анкет, склёпаных ботом за ночь, не помешает.

3. Тут зависит от подачи — если это будет где-то в сайдбаре, в низу, то мешать не будет 100%. Для слабых устройств подобное приложение это must have. Тем более, что возможности типа оффлайн-ридера и TTS — это круто. 

4. Фильтр правок — это штука, которая будет отмечать подозрительную активность и фильтровать разрещённые и запрещённые действия. Например — никому в здравом уме не прийдёт в голову сносить больше 80% страницы, ничем её не замення или вносить одну и ту же правку на множество страниц несколько раз в секунду.

5. Я говорю про запрет регестрации а не чтения/входа. Чтобы не плодили альты. В случае, если реальный человек по какой-то причине всё же вынужден заходить через такую опу., то пусть напишет на почту АМС и пояснит ситуацию — ему оформят аккаунт "вручную". 

6. То есть, фактически, перевод аккаунта в read only. Ибо совсем банить нет смысла.

**Comment by User-green** [comment]
4. Хорошо. Пока оставим, потом будет видно, надо оно или нет. Как-ни-как сделать всегда успеется. 
5. Не было? Ботнет FF, как минимум. 
6. Думаю, это стоит вынести в отдельную проблему.

**Comment by jewalky** [comment]
Закрыто за завершением чеклиста.
