### ISSUE TITLE
Синтаксис ссылки ломает форматирование текста

### ISSUE THREAD

**Issue by Rhombus-H** [SCPru/RuFoundation#41]
Пример - https://scpfoundation.net/scp-3034
При написании вместо "**[**//Шуршание бумагой.//**]**" появляется текст "[бумагой.//**]" с ссылкой на https://scpfoundation.net/*//шуршание

**Comment by jewalky** [comment]
Теперь вы никогда не сможете писать русскими буквами в ссылке (рип википедия)

**Comment by jewalky** [comment]
Ревертнуто. Не пишите такую хуйню. Викидот тоже ломает форматирование в этом месте

**Comment by jewalky** [comment]
Это можно обойти примерно так
```
@@[@@//Шуршание бумагой.//@@]@@
```
