### ISSUE TITLE
Некорректная работа компонента image-feature

### ISSUE THREAD

**Issue by AurelianLorgar** [SCPru/RuFoundation#43]
https://scpfoundation.net/component:image-features
Визуальные эффекты не работают начиная со Slide Image Revealer

**Comment by jewalky** [comment]
Посмотрю, но судя по ошибкам в консоли данный компонент делает какую-то ядрёную дичь.

В первый раз вижу обращение к local--html, а оно ещё и пытается что-то откуда-то читать `document.requestStorageAccess() may not be called on a document with an opaque origin, such as a sandboxed iframe without allow-same-origin in its sandbox attribute.`

**Comment by jewalky** [comment]
Короче ошибку я починил, но этот пиздец нормально работать не будет в целом

Как минимум нужно найти все места где используются хаки синтаксиса типа `[[!-- {$...} ` или `[[div_ class="[[#if ... | ... | ...]]"]]`

Очень тяжёлый код, я в него точно сейчас не полезу. Но сайт не виноват что викидот дерьмо
