### ISSUE TITLE
Ошибка отдачи mp3 с сервера

### ISSUE THREAD

**Issue by raf444** [SCPru/RuFoundation#44]
при использовании html audio в статье для воспроизведения mp3 файлов находящихся на ruFoundation сервере 
возникают следующие ошибки:
на браузере chromium невозможно перемотать аудиодорожку в плеере (возможно только слушать и ставить на паузу)
в консоле браузера была замечена ошибка при подгрузке mp3 файла (:ERR_QUIC_PROTOCOL_ERROR)

в браузере firefox возможно перематывать аудиодорожку но ползунок дергается после перемотки
(наверное неправильно оценивает длительность файла)

при использовании url mp3 файла с другого сервера, все работает нормально в обоих браузерах
https://scpfoundation.net/draft:mawak
тут пример бага

**Comment by jewalky** [comment]
Проблема на вашей стороне, выключите QUIC или ещё что-нибудь в этом роде
