### ISSUE TITLE
Нет всплывающих подсказок в footnote

### ISSUE THREAD

**Issue by AurelianLorgar** [SCPru/RuFoundation#47]
При наведении курсора на цифру сноски ничего не отображается. Текст в сноске можно прочитать, только если внизу страницы находится соответствующее поле.
Пример в черновике: https://scpfoundation.net/draft:dannan

**Comment by jewalky** [comment]
Не столько неправильное, сколько просто отсутствует скрипт который должен это делать. Будет поправлено в какой-то момент

**Comment by jewalky** [comment]
https://scpfoundation.net/scp-2342 этот объект полностью ломается
