### ISSUE TITLE
Нет модуля MailForm 

### ISSUE THREAD

**Issue by Int096** [SCPru/RuFoundation#49]
Нет модуля MailForm. 
На викидоте он есть с частности тут: http://scp-ru.wikidot.com/scp-6010, http://scp-ru.wikidot.com/sandbox:scp-6152

**Comment by jewalky** [comment]
Не приоритетно, это какая-то дырявая и небезопасная фигня которую используют не по назначению
MailForm должен использоваться для ОТПРАВКИ формы а не для её имитации. Это в названии.

**Comment by jewalky** [comment]
Переделывайте все такие формы на что-то типа такого
[[html]]
<b>логин:</b>
<input type="text">
<b>пароль:</b>
<input type="password">
[[/html]]
