### ISSUE TITLE
Блок фотографий поехал по высоте

### ISSUE THREAD

**Issue by ParussMan** [SCPru/RuFoundation#51]
Блоки фотографий в статьях поехали вверх и вниз, пример https://scpfoundation.net/scp-1130-ru

**Comment by jewalky** [comment]
В таких случаях заменять [[div]] на [[div_]]
Это связано с тем, что я убрал хак с параграфами и теперь без [[div_]] внутри блока генерируются параграфы.

**Comment by ParussMan** [comment]
> В таких случаях заменять [[div]] на [[div_]] Это связано с тем, что я убрал хак с параграфами и теперь без [[div_]] внутри блока генерируются параграфы.

Это опять в каждой статье ручками писать?( За что ты так с нами?
