### ISSUE TITLE
В теме BHL заполовинено левое меню (Фото)

### ISSUE THREAD

**Issue by Int096** [SCPru/RuFoundation#53]
https://scpfoundation.net/theme:black-highlighter-theme

Для сравнения (текста)

![изображение](https://user-images.githubusercontent.com/104515852/184494930-2fb826ef-77ac-4b37-982f-da308da1d27f.png)
![изображение](https://user-images.githubusercontent.com/104515852/184494943-76b3a5f5-7b46-4e8f-9b9c-9282bff24da4.png)

При наведении выделяется половина строки

**Comment by jewalky** [comment]
Исправлено, но вообще проблема была на стороне кода статьи.
Это было из-за <p>, т.е. часть элементов (пункты меню) надо было переделать из [[div]] в [[div_]].
см. мои правки на статье
