### ISSUE TITLE
Проблемы и баги сайта (НЕ ДОБАВЛЯЙТЕ НОВЫЕ БАГИ ЗДЕСЬ)

### ISSUE THREAD

**Issue by User-green** [SCPru/RuFoundation#6]
- [x] Нет модулей:
  - [x] `countpages`

- [x] "Случайная статья" не пашет
- [x] "Список по рейтингу" ожидаемо мёртв
- [x] В " Недавно созданные статьи " в колонке "Пользователь" везде одна и та же строка: `Пользователь 'system' не существует`

Бегло — всё.

**Comment by jewalky** [comment]
Дополнение:

Вот тут список попердолило https://scpfoundation.net/log-of-anomalous-items
Из-за того что в моём движке `--....\n...--` — валидная конструкция, а в викидоте нет.
Из-за этого автор использовал эту конструкцию ожидая что она не сработает, и если она срабатывает то всё ломается.

Фикс — сделать все инлайн тэги подобного рода с ограничением по строке

**Comment by jewalky** [comment]
> В канон-хабе "конца Смерти" нет компонента:
> 
>     * [ ]  `:scp-wiki:component:earthworm`

Не относится к новому сайту, это дебильные инклуды с других сайтов

**Comment by User-green** [comment]
> > В канон-хабе "конца Смерти" нет компонента:
> > 
> >     * [ ]  `:scp-wiki:component:earthworm`
> 
> Не относится к новому сайту, это дебильные инклуды с других сайтов

Может, стоит сделать инклюды, но кешыроемые локально? В целях обратной совместимости.

**Comment by jewalky** [comment]
тут ПИЗДЕЦ

https://scpfoundation.net/scp-template/noredirect/true

Почти ни один тэг [[code]] не работает как надо, в итоге редирект на www.пример.com автоматом происходит
