### ISSUE TITLE
Верхний и нижний модули по-разному округляют рейтинг

### ISSUE THREAD

**Issue by night-treason** [SCPru/RuFoundation#60]
Конкретно тот, в котором дробная часть оканчивается на 5. Верхний округляет вниз, а нижний - вверх. Мб из-за спринтф'а
Пример: https://scpfoundation.net/scp-6572

**Comment by jewalky** [comment]
Это из-за того, что в питоне и джсе принципиально по-разному работает округление. Привёл всё к питону
