### ISSUE TITLE
Не отображаются результаты своего голосования в модуле голосования

### ISSUE THREAD

**Issue by sanovskiy** [SCPru/RuFoundation#62]
![image](https://user-images.githubusercontent.com/4635300/184553687-89fc7916-3a75-464d-ba21-0640a1e198bc.png)
Результат голосования не отображается в модуле, позволяя совершить повторную попытку голосования. При повторной попытке голосования выдает ошибку на скрине.

**Comment by jewalky** [comment]
Возможно исправлено, не знаю, надо проверить с твоим юзером. У меня не воспроизводится.

**Comment by sanovskiy** [comment]
Ошибка больше не воспроизводится, но результат моего голосования так и не отображается.
