### ISSUE TITLE
Нет фичи show="true" у [[module css]]

### ISSUE THREAD

**Issue by Int096** [SCPru/RuFoundation#67]
Пример - https://scp-wiki.wikidot.com/theme:magnus-web-format

**Comment by jewalky** [comment]
Очень сложная фигня, для расколдовывания требует добавления синтаксиса по типу такого
```
[[set showCSS false]]
[[iftags +визуальная_тема]]
[[set showCSS true]]
[[/iftags]]
[[module CSS show="{$showCSS}"]]
...
[[/module]]
```

В данный момент не поддерживается, если что
