### ISSUE TITLE
Нет фичи /edit/true (?)

### ISSUE THREAD

**Issue by Int096** [SCPru/RuFoundation#68]
Когда нет компонента видим: 
![изображение](https://user-images.githubusercontent.com/104515852/184676599-88f73ed0-161b-4d5c-8a0e-03c2d02319a7.png)
Тыкаем на "создать сейчас" и нас кидает на страницу нужную с адресом https://scpfoundation.net/theme:test-test/edit/true (просто пример ссылки). На викидоте при этом открывалось окошечко редактирования, у нас такого нет.

**Comment by MrNereof** [comment]
Теперь есть
