### ISSUE TITLE
Ошибка отображения визуальной темы

### ISSUE THREAD

**Issue by AurelianLorgar** [SCPru/RuFoundation#72]
На странице хаба - https://scpfoundation.net/second-hytoth-hub - должна отображаться соответствующая визуальная тема, но вместо этого пишет, что её нет, и предлагает создать страницу, при том, что сама тема существует - https://scpfoundation.net/theme:hytoth

**Comment by jewalky** [comment]
Что-то не так со страницей

Почему в самом начале theme:hytoth написано `[[include theme:hytoth]]`?
