### ISSUE TITLE
В "Penumbra Theme" не отображается обратная ссылка с "Анима Сола"

### ISSUE THREAD

**Issue by JohnLyetacker** [SCPru/RuFoundation#73]
Среди обратных ссылок "Penumbra Theme", "Включения (используя [[include]])" отсутствует ссылка на "SCP-1170-RU - Анима Сола", который использует эту тему через include
https://scpfoundation.net/theme:penumbra
https://scpfoundation.net/scp-1170-ru
![изображение](https://user-images.githubusercontent.com/44590586/185128337-ea528a26-a7e1-4a75-87e4-e0027cce19e5.png)

**Comment by jewalky** [comment]
Фиг знает как это получилось, я в итоге отредактировал аниму солу и обратная ссылка появилась
