### ISSUE TITLE
Несоответствие ссылок с викидотом -  [[[Документ ]]]

### ISSUE THREAD

**Issue by raf444** [SCPru/RuFoundation#77]
https://scpfoundation.net/scp-1005
[[[Документ 1005-01478]]] - ведет на https://scpfoundation.net/1005-01478

http://scp-ru.wikidot.com/scp-1005
[[[Документ 1005-01478]]] - ведет на http://scp-ru.wikidot.com/dokument-1005-01478

**Comment by jewalky** [comment]
ебать жесть

ладно))

**Comment by jewalky** [comment]
Распопердолено в c74b36f и afa976a
