### ISSUE TITLE
Страница не рендерит код выше строки, в которой задана смена цвета через ##color|##

### ISSUE THREAD

**Issue by MaestroGame** [SCPru/RuFoundation#79]
~~Если написать где-либо на странице ##color|text## — страница выше этой строки рендерится как обычный текст.~~

##colot|text## взаимодействует с ## на странице ранее.
Например, от "SCP-####-RU" до "##colot|text##" на странице всё схлопнется и даже не станет рендерится.

**Comment by jewalky** [comment]
Исправлено при переезде на новый парсер
