### ISSUE TITLE
Все филиалы под одной крышей?

### ISSUE THREAD

**Issue by User-green** [SCPru/RuFoundation#8]
Идея такова. Домен `scpfoundation.net` становится общим. Для каждого филиала выделяется домен третьего уровня, который работает с сервером филиала (например `ru.scpfoundation.net A 222.222.222, en.scpfoundation.net A 111.111.111.111`).
Все, кто приходят на корневой домен рассылаются на филиалы согласно геопозиции и языку браузера.

Полигоны всех филиалов размещяются на доменах четвёртого уровня по схеме `sandbox.*.scpfoundation.net`.

Сам домен `scpfoundation.net` становится доменом-редеректором.

Да, я в курсе что это капитально, и что меня пошлют, но предложить-то можно.

**Comment by jewalky** [comment]
Мы это уже решали в закрытом чате.

Коллективно против: слишком большая ответственность
