### ISSUE TITLE
Пользовательский шрифт, загруженный на хостинг, не опознаётся из-за nosniff

### ISSUE THREAD

**Issue by MaestroGame** [SCPru/RuFoundation#81]
Ошибка из консоли, для примера:

Ресурс с «https://files.scpfoundation.net/local--files/draft:maestrogame/opirusopikregular-rgdv.woff» был заблокирован из-за несоответствия MIME-типа («font/woff») (X-Content-Type-Options: nosniff).

**Comment by JohnLyetacker** [comment]
![изображение](https://user-images.githubusercontent.com/44590586/209160081-6fd228aa-c135-4d65-812e-e2ec093caea7.png)
downloadable font: download failed (font-family: "Bauhaus" style:normal weight:400 stretch:100 src index:2): bad URI or cross-site access not allowed source: https://scpfoundation.net/local--files/theme:s5/bauhaus.woff
