### ISSUE TITLE
Проблема с исходником правки при изменении заголовка

### ISSUE THREAD

**Issue by ParussMan** [SCPru/RuFoundation#93]
Если в правке изменяется только заголовок, то при попытке просмотреть ее исходный код открывается код самой первой правки

Пример можно глянуть здесь https://scpfoundation.net/scp-055

**Comment by ParussMan** [comment]
Апдейт на всякий, не только с изменением заголовка, а с любым изменением не затрагивающим текст статьи, т.е. теги, файлы и т.п.

**Comment by Rhombus-H** [comment]
Невоспроизводимо, всё работает.
