### ISSUE TITLE
Не работает сворачивание блоков  в статье SCP-3199 

### ISSUE THREAD

**Issue by Liirsh** [SCPru/RuFoundation#94]
ссылка на статью: 
https://scpfoundation.net/scp-3199
пример: 
![image](https://user-images.githubusercontent.com/112322085/187071599-07933061-0b23-4284-904c-8409bfe337a0.png)

**Comment by jewalky** [comment]
Потому что `[[/collapsible]]` должно быть на отдельной строке, а не так:
```
[[collapsible]]
> ....... [[/collapsible]]
```
