### ISSUE TITLE
Нельзя записать несколько [[footnote]] подряд в строчку

### ISSUE THREAD

**Issue by Rhombus-H** [SCPru/RuFoundation#97]
При попытке записать несколько сносок в строчку подряд блоками вида:
[[footnote]]
x
[[/footnote]]
[[footnote]]
...
Сноски идут не в строчку последовательно, а разбрасываются друг под другом вертикально как на пикриле
![image](https://user-images.githubusercontent.com/83302661/187435109-3835a2f5-f075-4619-acbc-4758a6f0526f.png)
Должно быть пикрил2
![image](https://user-images.githubusercontent.com/83302661/187435165-1a3e4ce0-b3e6-4831-899a-91af9e05f764.png)

**Comment by jewalky** [comment]
Можно, просто если ты хочешь сноски в строчку, нужно писать их в строчку, а не с переносами строки ))
