### ISSUE TITLE
Некорректное отображение звёзд в рейтинге

### ISSUE THREAD

**Issue by AUSTILGUNG** [SCPru/RuFoundation#99]
Как минимум в статье https://scpfoundation.net/scp-1415-ru некорректно отображается количество звезд в окне рейтинга внизу страницы (4.0 отображается как 4 с лишним звезды), в модуле рейтинга сверху страницы все отображается корректно.
![Screenshot_20220830-170701_Chrome](https://user-images.githubusercontent.com/111248610/187459006-c152fc24-6fc4-4c54-a2e0-63e1619e962d.jpg)

**Comment by MrNereof** [comment]
Не воспроизводимо
